apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
    selector:
        matchLabels:
            app: back-end
    replicas: 5
    template:
        metadata:
            labels:
                app: back-end
        spec:
            containers:
                - name: back-end
                image: garimanath/node_test:latest
                ports:
                    - containerPort: 80


#service file
apiVersion: v1
kind: Service
metadata:
    name: node-service
spec:
    selector:
        app: back-end
    ports:
    - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 31000
    type: NodePort